[req]
distinguished_name = req_distinguished_name
req_extensions = v3_req
prompt = no

[req_distinguished_name]
CN = sidecar-injector.webhook-system.svc

[v3_req]
subjectAltName = DNS:sidecar-injector.webhook-system.svc,DNS:sidecar-injector.webhook-system,DNS:localhost,IP:127.0.0.1
