// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: pkg/ctrl/mesh/mesh.proto

package mesh

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpType int32

const (
	OpType_ADDED    OpType = 0
	OpType_DELETED  OpType = 1
	OpType_MODIFIED OpType = 2
)

// Enum value maps for OpType.
var (
	OpType_name = map[int32]string{
		0: "ADDED",
		1: "DELETED",
		2: "MODIFIED",
	}
	OpType_value = map[string]int32{
		"ADDED":    0,
		"DELETED":  1,
		"MODIFIED": 2,
	}
)

func (x OpType) Enum() *OpType {
	p := new(OpType)
	*p = x
	return p
}

func (x OpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_ctrl_mesh_mesh_proto_enumTypes[0].Descriptor()
}

func (OpType) Type() protoreflect.EnumType {
	return &file_pkg_ctrl_mesh_mesh_proto_enumTypes[0]
}

func (x OpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpType.Descriptor instead.
func (OpType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_ctrl_mesh_mesh_proto_rawDescGZIP(), []int{0}
}

type EndpointIPs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndpointIps   []string               `protobuf:"bytes,1,rep,name=endpoint_ips,json=endpointIps,proto3" json:"endpoint_ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointIPs) Reset() {
	*x = EndpointIPs{}
	mi := &file_pkg_ctrl_mesh_mesh_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointIPs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointIPs) ProtoMessage() {}

func (x *EndpointIPs) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ctrl_mesh_mesh_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointIPs.ProtoReflect.Descriptor instead.
func (*EndpointIPs) Descriptor() ([]byte, []int) {
	return file_pkg_ctrl_mesh_mesh_proto_rawDescGZIP(), []int{0}
}

func (x *EndpointIPs) GetEndpointIps() []string {
	if x != nil {
		return x.EndpointIps
	}
	return nil
}

type ClientSubscriptionEvent struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Revision      int64                   `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	OpType        OpType                  `protobuf:"varint,2,opt,name=op_type,json=opType,proto3,enum=mesh.OpType" json:"op_type,omitempty"`
	Endpoints     map[string]*EndpointIPs `protobuf:"bytes,3,rep,name=endpoints,proto3" json:"endpoints,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientSubscriptionEvent) Reset() {
	*x = ClientSubscriptionEvent{}
	mi := &file_pkg_ctrl_mesh_mesh_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientSubscriptionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSubscriptionEvent) ProtoMessage() {}

func (x *ClientSubscriptionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ctrl_mesh_mesh_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSubscriptionEvent.ProtoReflect.Descriptor instead.
func (*ClientSubscriptionEvent) Descriptor() ([]byte, []int) {
	return file_pkg_ctrl_mesh_mesh_proto_rawDescGZIP(), []int{1}
}

func (x *ClientSubscriptionEvent) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *ClientSubscriptionEvent) GetOpType() OpType {
	if x != nil {
		return x.OpType
	}
	return OpType_ADDED
}

func (x *ClientSubscriptionEvent) GetEndpoints() map[string]*EndpointIPs {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type SubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SidecarId     string                 `protobuf:"bytes,1,opt,name=sidecar_id,json=sidecarId,proto3" json:"sidecar_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionRequest) Reset() {
	*x = SubscriptionRequest{}
	mi := &file_pkg_ctrl_mesh_mesh_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionRequest) ProtoMessage() {}

func (x *SubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ctrl_mesh_mesh_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionRequest.ProtoReflect.Descriptor instead.
func (*SubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_ctrl_mesh_mesh_proto_rawDescGZIP(), []int{2}
}

func (x *SubscriptionRequest) GetSidecarId() string {
	if x != nil {
		return x.SidecarId
	}
	return ""
}

func (x *SubscriptionRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

var File_pkg_ctrl_mesh_mesh_proto protoreflect.FileDescriptor

const file_pkg_ctrl_mesh_mesh_proto_rawDesc = "" +
	"\n" +
	"\x18pkg/ctrl/mesh/mesh.proto\x12\x04mesh\"0\n" +
	"\vEndpointIPs\x12!\n" +
	"\fendpoint_ips\x18\x01 \x03(\tR\vendpointIps\"\xf9\x01\n" +
	"\x17ClientSubscriptionEvent\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x03R\brevision\x12%\n" +
	"\aop_type\x18\x02 \x01(\x0e2\f.mesh.OpTypeR\x06opType\x12J\n" +
	"\tendpoints\x18\x03 \x03(\v2,.mesh.ClientSubscriptionEvent.EndpointsEntryR\tendpoints\x1aO\n" +
	"\x0eEndpointsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.mesh.EndpointIPsR\x05value:\x028\x01\"W\n" +
	"\x13SubscriptionRequest\x12\x1d\n" +
	"\n" +
	"sidecar_id\x18\x01 \x01(\tR\tsidecarId\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName*.\n" +
	"\x06OpType\x12\t\n" +
	"\x05ADDED\x10\x00\x12\v\n" +
	"\aDELETED\x10\x01\x12\f\n" +
	"\bMODIFIED\x10\x022S\n" +
	"\bMeshCtrl\x12G\n" +
	"\tSubscribe\x12\x19.mesh.SubscriptionRequest\x1a\x1d.mesh.ClientSubscriptionEvent0\x01B\x14Z\x12pkg/ctrl/mesh;meshb\x06proto3"

var (
	file_pkg_ctrl_mesh_mesh_proto_rawDescOnce sync.Once
	file_pkg_ctrl_mesh_mesh_proto_rawDescData []byte
)

func file_pkg_ctrl_mesh_mesh_proto_rawDescGZIP() []byte {
	file_pkg_ctrl_mesh_mesh_proto_rawDescOnce.Do(func() {
		file_pkg_ctrl_mesh_mesh_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_ctrl_mesh_mesh_proto_rawDesc), len(file_pkg_ctrl_mesh_mesh_proto_rawDesc)))
	})
	return file_pkg_ctrl_mesh_mesh_proto_rawDescData
}

var file_pkg_ctrl_mesh_mesh_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_ctrl_mesh_mesh_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_ctrl_mesh_mesh_proto_goTypes = []any{
	(OpType)(0),                     // 0: mesh.OpType
	(*EndpointIPs)(nil),             // 1: mesh.EndpointIPs
	(*ClientSubscriptionEvent)(nil), // 2: mesh.ClientSubscriptionEvent
	(*SubscriptionRequest)(nil),     // 3: mesh.SubscriptionRequest
	nil,                             // 4: mesh.ClientSubscriptionEvent.EndpointsEntry
}
var file_pkg_ctrl_mesh_mesh_proto_depIdxs = []int32{
	0, // 0: mesh.ClientSubscriptionEvent.op_type:type_name -> mesh.OpType
	4, // 1: mesh.ClientSubscriptionEvent.endpoints:type_name -> mesh.ClientSubscriptionEvent.EndpointsEntry
	1, // 2: mesh.ClientSubscriptionEvent.EndpointsEntry.value:type_name -> mesh.EndpointIPs
	3, // 3: mesh.MeshCtrl.Subscribe:input_type -> mesh.SubscriptionRequest
	2, // 4: mesh.MeshCtrl.Subscribe:output_type -> mesh.ClientSubscriptionEvent
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_ctrl_mesh_mesh_proto_init() }
func file_pkg_ctrl_mesh_mesh_proto_init() {
	if File_pkg_ctrl_mesh_mesh_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_ctrl_mesh_mesh_proto_rawDesc), len(file_pkg_ctrl_mesh_mesh_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_ctrl_mesh_mesh_proto_goTypes,
		DependencyIndexes: file_pkg_ctrl_mesh_mesh_proto_depIdxs,
		EnumInfos:         file_pkg_ctrl_mesh_mesh_proto_enumTypes,
		MessageInfos:      file_pkg_ctrl_mesh_mesh_proto_msgTypes,
	}.Build()
	File_pkg_ctrl_mesh_mesh_proto = out.File
	file_pkg_ctrl_mesh_mesh_proto_goTypes = nil
	file_pkg_ctrl_mesh_mesh_proto_depIdxs = nil
}
