// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/api/mesh/mesh.proto

package mesh

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// sidecar 订阅/查询他们所需要的服务
type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_pkg_api_mesh_mesh_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_mesh_mesh_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_mesh_mesh_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *SubscribeRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

// controller 推给 sidecar 的单个服务端口
type Endpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_pkg_api_mesh_mesh_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_mesh_mesh_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_pkg_api_mesh_mesh_proto_rawDescGZIP(), []int{1}
}

func (x *Endpoint) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Endpoint) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// controller 推给 sidecar 的服务信息
type ServiceUpdate struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	OpType string                 `protobuf:"bytes,1,opt,name=op_type,json=opType,proto3" json:"op_type,omitempty"`
	// key: endpoint_uid, value: Endpoint
	Endpoints     map[string]*Endpoint `protobuf:"bytes,2,rep,name=endpoints,proto3" json:"endpoints,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceUpdate) Reset() {
	*x = ServiceUpdate{}
	mi := &file_pkg_api_mesh_mesh_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceUpdate) ProtoMessage() {}

func (x *ServiceUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_mesh_mesh_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceUpdate.ProtoReflect.Descriptor instead.
func (*ServiceUpdate) Descriptor() ([]byte, []int) {
	return file_pkg_api_mesh_mesh_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceUpdate) GetOpType() string {
	if x != nil {
		return x.OpType
	}
	return ""
}

func (x *ServiceUpdate) GetEndpoints() map[string]*Endpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

var File_pkg_api_mesh_mesh_proto protoreflect.FileDescriptor

const file_pkg_api_mesh_mesh_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/api/mesh/mesh.proto\x12\x04mesh\"V\n" +
	"\x10SubscribeRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\".\n" +
	"\bEndpoint\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\"\xb8\x01\n" +
	"\rServiceUpdate\x12\x17\n" +
	"\aop_type\x18\x01 \x01(\tR\x06opType\x12@\n" +
	"\tendpoints\x18\x02 \x03(\v2\".mesh.ServiceUpdate.EndpointsEntryR\tendpoints\x1aL\n" +
	"\x0eEndpointsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.mesh.EndpointR\x05value:\x028\x012\xc0\x01\n" +
	"\vControlFace\x12:\n" +
	"\tSubscribe\x12\x16.mesh.SubscribeRequest\x1a\x13.mesh.ServiceUpdate0\x01\x129\n" +
	"\n" +
	"Unsubsribe\x12\x16.mesh.SubscribeRequest\x1a\x13.mesh.ServiceUpdate\x12:\n" +
	"\vListService\x12\x16.mesh.SubscribeRequest\x1a\x13.mesh.ServiceUpdateB\x13Z\x11pkg/api/mesh;meshb\x06proto3"

var (
	file_pkg_api_mesh_mesh_proto_rawDescOnce sync.Once
	file_pkg_api_mesh_mesh_proto_rawDescData []byte
)

func file_pkg_api_mesh_mesh_proto_rawDescGZIP() []byte {
	file_pkg_api_mesh_mesh_proto_rawDescOnce.Do(func() {
		file_pkg_api_mesh_mesh_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_mesh_mesh_proto_rawDesc), len(file_pkg_api_mesh_mesh_proto_rawDesc)))
	})
	return file_pkg_api_mesh_mesh_proto_rawDescData
}

var file_pkg_api_mesh_mesh_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_api_mesh_mesh_proto_goTypes = []any{
	(*SubscribeRequest)(nil), // 0: mesh.SubscribeRequest
	(*Endpoint)(nil),         // 1: mesh.Endpoint
	(*ServiceUpdate)(nil),    // 2: mesh.ServiceUpdate
	nil,                      // 3: mesh.ServiceUpdate.EndpointsEntry
}
var file_pkg_api_mesh_mesh_proto_depIdxs = []int32{
	3, // 0: mesh.ServiceUpdate.endpoints:type_name -> mesh.ServiceUpdate.EndpointsEntry
	1, // 1: mesh.ServiceUpdate.EndpointsEntry.value:type_name -> mesh.Endpoint
	0, // 2: mesh.ControlFace.Subscribe:input_type -> mesh.SubscribeRequest
	0, // 3: mesh.ControlFace.Unsubsribe:input_type -> mesh.SubscribeRequest
	0, // 4: mesh.ControlFace.ListService:input_type -> mesh.SubscribeRequest
	2, // 5: mesh.ControlFace.Subscribe:output_type -> mesh.ServiceUpdate
	2, // 6: mesh.ControlFace.Unsubsribe:output_type -> mesh.ServiceUpdate
	2, // 7: mesh.ControlFace.ListService:output_type -> mesh.ServiceUpdate
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_api_mesh_mesh_proto_init() }
func file_pkg_api_mesh_mesh_proto_init() {
	if File_pkg_api_mesh_mesh_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_mesh_mesh_proto_rawDesc), len(file_pkg_api_mesh_mesh_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_mesh_mesh_proto_goTypes,
		DependencyIndexes: file_pkg_api_mesh_mesh_proto_depIdxs,
		MessageInfos:      file_pkg_api_mesh_mesh_proto_msgTypes,
	}.Build()
	File_pkg_api_mesh_mesh_proto = out.File
	file_pkg_api_mesh_mesh_proto_goTypes = nil
	file_pkg_api_mesh_mesh_proto_depIdxs = nil
}
