// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/api/mesh/mesh.proto

package mesh

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_pkg_api_mesh_mesh_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_mesh_mesh_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_mesh_mesh_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *SubscribeRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type Endpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Addresses     []string               `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_pkg_api_mesh_mesh_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_mesh_mesh_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_pkg_api_mesh_mesh_proto_rawDescGZIP(), []int{1}
}

func (x *Endpoint) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *Endpoint) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type ServiceConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      int64                  `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Endpoints     []*Endpoint            `protobuf:"bytes,5,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceConfig) Reset() {
	*x = ServiceConfig{}
	mi := &file_pkg_api_mesh_mesh_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceConfig) ProtoMessage() {}

func (x *ServiceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_mesh_mesh_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceConfig.ProtoReflect.Descriptor instead.
func (*ServiceConfig) Descriptor() ([]byte, []int) {
	return file_pkg_api_mesh_mesh_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceConfig) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *ServiceConfig) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceConfig) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServiceConfig) GetEndpoints() []*Endpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type UnSubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnSubscribeRequest) Reset() {
	*x = UnSubscribeRequest{}
	mi := &file_pkg_api_mesh_mesh_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnSubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnSubscribeRequest) ProtoMessage() {}

func (x *UnSubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_mesh_mesh_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnSubscribeRequest.ProtoReflect.Descriptor instead.
func (*UnSubscribeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_mesh_mesh_proto_rawDescGZIP(), []int{3}
}

func (x *UnSubscribeRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *UnSubscribeRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type UnSubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnSubscribeResponse) Reset() {
	*x = UnSubscribeResponse{}
	mi := &file_pkg_api_mesh_mesh_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnSubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnSubscribeResponse) ProtoMessage() {}

func (x *UnSubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_mesh_mesh_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnSubscribeResponse.ProtoReflect.Descriptor instead.
func (*UnSubscribeResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_mesh_mesh_proto_rawDescGZIP(), []int{4}
}

func (x *UnSubscribeResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_pkg_api_mesh_mesh_proto protoreflect.FileDescriptor

const file_pkg_api_mesh_mesh_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/api/mesh/mesh.proto\x12\x04mesh\"V\n" +
	"\x10SubscribeRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\"I\n" +
	"\bEndpoint\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1c\n" +
	"\taddresses\x18\x02 \x03(\tR\taddresses\"\x96\x01\n" +
	"\rServiceConfig\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x03R\brevision\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12,\n" +
	"\tendpoints\x18\x05 \x03(\v2\x0e.mesh.EndpointR\tendpoints\"X\n" +
	"\x12UnSubscribeRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\"'\n" +
	"\x13UnSubscribeResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg2\x8c\x01\n" +
	"\n" +
	"Controller\x12:\n" +
	"\tSubscribe\x12\x16.mesh.SubscribeRequest\x1a\x13.mesh.ServiceConfig0\x01\x12B\n" +
	"\vUnSubscribe\x12\x18.mesh.UnSubscribeRequest\x1a\x19.mesh.UnSubscribeResponseB\x13Z\x11pkg/api/mesh;meshb\x06proto3"

var (
	file_pkg_api_mesh_mesh_proto_rawDescOnce sync.Once
	file_pkg_api_mesh_mesh_proto_rawDescData []byte
)

func file_pkg_api_mesh_mesh_proto_rawDescGZIP() []byte {
	file_pkg_api_mesh_mesh_proto_rawDescOnce.Do(func() {
		file_pkg_api_mesh_mesh_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_mesh_mesh_proto_rawDesc), len(file_pkg_api_mesh_mesh_proto_rawDesc)))
	})
	return file_pkg_api_mesh_mesh_proto_rawDescData
}

var file_pkg_api_mesh_mesh_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_api_mesh_mesh_proto_goTypes = []any{
	(*SubscribeRequest)(nil),    // 0: mesh.SubscribeRequest
	(*Endpoint)(nil),            // 1: mesh.Endpoint
	(*ServiceConfig)(nil),       // 2: mesh.ServiceConfig
	(*UnSubscribeRequest)(nil),  // 3: mesh.UnSubscribeRequest
	(*UnSubscribeResponse)(nil), // 4: mesh.UnSubscribeResponse
}
var file_pkg_api_mesh_mesh_proto_depIdxs = []int32{
	1, // 0: mesh.ServiceConfig.endpoints:type_name -> mesh.Endpoint
	0, // 1: mesh.Controller.Subscribe:input_type -> mesh.SubscribeRequest
	3, // 2: mesh.Controller.UnSubscribe:input_type -> mesh.UnSubscribeRequest
	2, // 3: mesh.Controller.Subscribe:output_type -> mesh.ServiceConfig
	4, // 4: mesh.Controller.UnSubscribe:output_type -> mesh.UnSubscribeResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_api_mesh_mesh_proto_init() }
func file_pkg_api_mesh_mesh_proto_init() {
	if File_pkg_api_mesh_mesh_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_mesh_mesh_proto_rawDesc), len(file_pkg_api_mesh_mesh_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_mesh_mesh_proto_goTypes,
		DependencyIndexes: file_pkg_api_mesh_mesh_proto_depIdxs,
		MessageInfos:      file_pkg_api_mesh_mesh_proto_msgTypes,
	}.Build()
	File_pkg_api_mesh_mesh_proto = out.File
	file_pkg_api_mesh_mesh_proto_goTypes = nil
	file_pkg_api_mesh_mesh_proto_depIdxs = nil
}
