// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.28.3
// source: pkg/ctrl/mesh/mesh.proto

package mesh

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MeshCtrl_Subscribe_FullMethodName = "/mesh.MeshCtrl/Subscribe"
)

// MeshCtrlClient is the client API for MeshCtrl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// control face of my mesh
type MeshCtrlClient interface {
	// for client's subscription
	Subscribe(ctx context.Context, in *SubscriptionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ClientSubscriptionEvent], error)
}

type meshCtrlClient struct {
	cc grpc.ClientConnInterface
}

func NewMeshCtrlClient(cc grpc.ClientConnInterface) MeshCtrlClient {
	return &meshCtrlClient{cc}
}

func (c *meshCtrlClient) Subscribe(ctx context.Context, in *SubscriptionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ClientSubscriptionEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MeshCtrl_ServiceDesc.Streams[0], MeshCtrl_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscriptionRequest, ClientSubscriptionEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MeshCtrl_SubscribeClient = grpc.ServerStreamingClient[ClientSubscriptionEvent]

// MeshCtrlServer is the server API for MeshCtrl service.
// All implementations must embed UnimplementedMeshCtrlServer
// for forward compatibility.
//
// control face of my mesh
type MeshCtrlServer interface {
	// for client's subscription
	Subscribe(*SubscriptionRequest, grpc.ServerStreamingServer[ClientSubscriptionEvent]) error
	mustEmbedUnimplementedMeshCtrlServer()
}

// UnimplementedMeshCtrlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMeshCtrlServer struct{}

func (UnimplementedMeshCtrlServer) Subscribe(*SubscriptionRequest, grpc.ServerStreamingServer[ClientSubscriptionEvent]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedMeshCtrlServer) mustEmbedUnimplementedMeshCtrlServer() {}
func (UnimplementedMeshCtrlServer) testEmbeddedByValue()                  {}

// UnsafeMeshCtrlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MeshCtrlServer will
// result in compilation errors.
type UnsafeMeshCtrlServer interface {
	mustEmbedUnimplementedMeshCtrlServer()
}

func RegisterMeshCtrlServer(s grpc.ServiceRegistrar, srv MeshCtrlServer) {
	// If the following call panics, it indicates UnimplementedMeshCtrlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MeshCtrl_ServiceDesc, srv)
}

func _MeshCtrl_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscriptionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MeshCtrlServer).Subscribe(m, &grpc.GenericServerStream[SubscriptionRequest, ClientSubscriptionEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MeshCtrl_SubscribeServer = grpc.ServerStreamingServer[ClientSubscriptionEvent]

// MeshCtrl_ServiceDesc is the grpc.ServiceDesc for MeshCtrl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MeshCtrl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mesh.MeshCtrl",
	HandlerType: (*MeshCtrlServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _MeshCtrl_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/ctrl/mesh/mesh.proto",
}
