// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: pkg/api/control_plane.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlPlane_GetServiceConfig_FullMethodName = "/api.ControlPlane/GetServiceConfig"
	ControlPlane_RegisterService_FullMethodName  = "/api.ControlPlane/RegisterService"
	ControlPlane_StreamConfig_FullMethodName     = "/api.ControlPlane/StreamConfig"
)

// ControlPlaneClient is the client API for ControlPlane service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ControlPlane service for managing sidecar configurations
type ControlPlaneClient interface {
	// Get service configuration
	GetServiceConfig(ctx context.Context, in *ServiceConfigRequest, opts ...grpc.CallOption) (*ServiceConfigResponse, error)
	// Register a service
	RegisterService(ctx context.Context, in *ServiceRegistration, opts ...grpc.CallOption) (*RegistrationResponse, error)
	// Stream configuration updates
	StreamConfig(ctx context.Context, in *ServiceConfigRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServiceConfigResponse], error)
}

type controlPlaneClient struct {
	cc grpc.ClientConnInterface
}

func NewControlPlaneClient(cc grpc.ClientConnInterface) ControlPlaneClient {
	return &controlPlaneClient{cc}
}

func (c *controlPlaneClient) GetServiceConfig(ctx context.Context, in *ServiceConfigRequest, opts ...grpc.CallOption) (*ServiceConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceConfigResponse)
	err := c.cc.Invoke(ctx, ControlPlane_GetServiceConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) RegisterService(ctx context.Context, in *ServiceRegistration, opts ...grpc.CallOption) (*RegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistrationResponse)
	err := c.cc.Invoke(ctx, ControlPlane_RegisterService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) StreamConfig(ctx context.Context, in *ServiceConfigRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServiceConfigResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlPlane_ServiceDesc.Streams[0], ControlPlane_StreamConfig_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ServiceConfigRequest, ServiceConfigResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_StreamConfigClient = grpc.ServerStreamingClient[ServiceConfigResponse]

// ControlPlaneServer is the server API for ControlPlane service.
// All implementations must embed UnimplementedControlPlaneServer
// for forward compatibility.
//
// ControlPlane service for managing sidecar configurations
type ControlPlaneServer interface {
	// Get service configuration
	GetServiceConfig(context.Context, *ServiceConfigRequest) (*ServiceConfigResponse, error)
	// Register a service
	RegisterService(context.Context, *ServiceRegistration) (*RegistrationResponse, error)
	// Stream configuration updates
	StreamConfig(*ServiceConfigRequest, grpc.ServerStreamingServer[ServiceConfigResponse]) error
	mustEmbedUnimplementedControlPlaneServer()
}

// UnimplementedControlPlaneServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlPlaneServer struct{}

func (UnimplementedControlPlaneServer) GetServiceConfig(context.Context, *ServiceConfigRequest) (*ServiceConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServiceConfig not implemented")
}
func (UnimplementedControlPlaneServer) RegisterService(context.Context, *ServiceRegistration) (*RegistrationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterService not implemented")
}
func (UnimplementedControlPlaneServer) StreamConfig(*ServiceConfigRequest, grpc.ServerStreamingServer[ServiceConfigResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamConfig not implemented")
}
func (UnimplementedControlPlaneServer) mustEmbedUnimplementedControlPlaneServer() {}
func (UnimplementedControlPlaneServer) testEmbeddedByValue()                      {}

// UnsafeControlPlaneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlPlaneServer will
// result in compilation errors.
type UnsafeControlPlaneServer interface {
	mustEmbedUnimplementedControlPlaneServer()
}

func RegisterControlPlaneServer(s grpc.ServiceRegistrar, srv ControlPlaneServer) {
	// If the following call panics, it indicates UnimplementedControlPlaneServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlPlane_ServiceDesc, srv)
}

func _ControlPlane_GetServiceConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).GetServiceConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_GetServiceConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).GetServiceConfig(ctx, req.(*ServiceConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_RegisterService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceRegistration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).RegisterService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_RegisterService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).RegisterService(ctx, req.(*ServiceRegistration))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_StreamConfig_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ServiceConfigRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlPlaneServer).StreamConfig(m, &grpc.GenericServerStream[ServiceConfigRequest, ServiceConfigResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_StreamConfigServer = grpc.ServerStreamingServer[ServiceConfigResponse]

// ControlPlane_ServiceDesc is the grpc.ServiceDesc for ControlPlane service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlPlane_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.ControlPlane",
	HandlerType: (*ControlPlaneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetServiceConfig",
			Handler:    _ControlPlane_GetServiceConfig_Handler,
		},
		{
			MethodName: "RegisterService",
			Handler:    _ControlPlane_RegisterService_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamConfig",
			Handler:       _ControlPlane_StreamConfig_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/api/control_plane.proto",
}
