// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/api/control_plane.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceConfigRequest) Reset() {
	*x = ServiceConfigRequest{}
	mi := &file_pkg_api_control_plane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceConfigRequest) ProtoMessage() {}

func (x *ServiceConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_control_plane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceConfigRequest.ProtoReflect.Descriptor instead.
func (*ServiceConfigRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_control_plane_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceConfigRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type ServiceConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Endpoints     []string               `protobuf:"bytes,2,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceConfigResponse) Reset() {
	*x = ServiceConfigResponse{}
	mi := &file_pkg_api_control_plane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceConfigResponse) ProtoMessage() {}

func (x *ServiceConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_control_plane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceConfigResponse.ProtoReflect.Descriptor instead.
func (*ServiceConfigResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_control_plane_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceConfigResponse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceConfigResponse) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *ServiceConfigResponse) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type ServiceRegistration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Endpoint      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceRegistration) Reset() {
	*x = ServiceRegistration{}
	mi := &file_pkg_api_control_plane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRegistration) ProtoMessage() {}

func (x *ServiceRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_control_plane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRegistration.ProtoReflect.Descriptor instead.
func (*ServiceRegistration) Descriptor() ([]byte, []int) {
	return file_pkg_api_control_plane_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceRegistration) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceRegistration) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type RegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationResponse) Reset() {
	*x = RegistrationResponse{}
	mi := &file_pkg_api_control_plane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationResponse) ProtoMessage() {}

func (x *RegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_control_plane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationResponse.ProtoReflect.Descriptor instead.
func (*RegistrationResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_control_plane_proto_rawDescGZIP(), []int{3}
}

func (x *RegistrationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegistrationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_api_control_plane_proto protoreflect.FileDescriptor

const file_pkg_api_control_plane_proto_rawDesc = "" +
	"\n" +
	"\x1bpkg/api/control_plane.proto\x12\x03api\"9\n" +
	"\x14ServiceConfigRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\"t\n" +
	"\x15ServiceConfigResponse\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x1c\n" +
	"\tendpoints\x18\x02 \x03(\tR\tendpoints\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\"T\n" +
	"\x13ServiceRegistration\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\"J\n" +
	"\x14RegistrationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xea\x01\n" +
	"\fControlPlane\x12I\n" +
	"\x10GetServiceConfig\x12\x19.api.ServiceConfigRequest\x1a\x1a.api.ServiceConfigResponse\x12F\n" +
	"\x0fRegisterService\x12\x18.api.ServiceRegistration\x1a\x19.api.RegistrationResponse\x12G\n" +
	"\fStreamConfig\x12\x19.api.ServiceConfigRequest\x1a\x1a.api.ServiceConfigResponse0\x01B'Z%github.com/BuMaRen/masha-mesh/pkg/apib\x06proto3"

var (
	file_pkg_api_control_plane_proto_rawDescOnce sync.Once
	file_pkg_api_control_plane_proto_rawDescData []byte
)

func file_pkg_api_control_plane_proto_rawDescGZIP() []byte {
	file_pkg_api_control_plane_proto_rawDescOnce.Do(func() {
		file_pkg_api_control_plane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_control_plane_proto_rawDesc), len(file_pkg_api_control_plane_proto_rawDesc)))
	})
	return file_pkg_api_control_plane_proto_rawDescData
}

var file_pkg_api_control_plane_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_api_control_plane_proto_goTypes = []any{
	(*ServiceConfigRequest)(nil),  // 0: api.ServiceConfigRequest
	(*ServiceConfigResponse)(nil), // 1: api.ServiceConfigResponse
	(*ServiceRegistration)(nil),   // 2: api.ServiceRegistration
	(*RegistrationResponse)(nil),  // 3: api.RegistrationResponse
}
var file_pkg_api_control_plane_proto_depIdxs = []int32{
	0, // 0: api.ControlPlane.GetServiceConfig:input_type -> api.ServiceConfigRequest
	2, // 1: api.ControlPlane.RegisterService:input_type -> api.ServiceRegistration
	0, // 2: api.ControlPlane.StreamConfig:input_type -> api.ServiceConfigRequest
	1, // 3: api.ControlPlane.GetServiceConfig:output_type -> api.ServiceConfigResponse
	3, // 4: api.ControlPlane.RegisterService:output_type -> api.RegistrationResponse
	1, // 5: api.ControlPlane.StreamConfig:output_type -> api.ServiceConfigResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_api_control_plane_proto_init() }
func file_pkg_api_control_plane_proto_init() {
	if File_pkg_api_control_plane_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_control_plane_proto_rawDesc), len(file_pkg_api_control_plane_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_control_plane_proto_goTypes,
		DependencyIndexes: file_pkg_api_control_plane_proto_depIdxs,
		MessageInfos:      file_pkg_api_control_plane_proto_msgTypes,
	}.Build()
	File_pkg_api_control_plane_proto = out.File
	file_pkg_api_control_plane_proto_goTypes = nil
	file_pkg_api_control_plane_proto_depIdxs = nil
}
